# Generated by Django 2.2.4 on 2020-12-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('attitude', models.TextField(default='')),
                ('latitude', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Basic')),
            ],
            bases=('api.basic',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Basic')),
            ],
            bases=('api.basic',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Basic')),
                ('summary', models.TextField(default='')),
            ],
            bases=('api.basic',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('basic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Basic')),
            ],
            bases=('api.basic',),
        ),
    ]
