# Generated by Django 2.2.4 on 2020-12-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic',
            old_name='attitude',
            new_name='longitude',
        ),
    ]
